### PR TITLE
PHP 7.0 - 7.3 support fixes

### PR DESCRIPTION
**Pull request by esminis**

### CODE REVIEW

**Comment by jangrewe** [comment]
Oh, i need these fixes. Any change to get the conflicts fixed and this PR merged? Thanks! =)

**Comment by esminis** [comment]
I have fixed the conflicts but have not tested code as for now

**Comment by esminis** [comment]
Now tests are passing for latest PHP versions and windows

**Comment by esminis** [comment]
All tests now passing

**Comment by jangrewe** [comment]
Thank you! :-)

**Comment by kkochanski** [comment]
Any chance for it?

**Comment by nsknewbie** [comment]
@cataphract we need this

**Comment by eaglemoor** [comment]
Up!

**Comment by iamsalnikov** [comment]
Please apply if it is possible

**Comment by Dibbyo456** [comment]
Anyone tested with PHP 7.4 ?

**Comment by esminis** [comment]
No - as there is no action on this merge request for years

**Comment by cioroianudenis** [comment]
Not supported in PHP 7.4, I tried in 7.4.5 and windows 7 apache xampp fail to open.

**Comment by cataphract** [comment]
Support for 7.2-7.4 was added in the 4.1.0 release.

**Pull request closed without merging**
