### PR TITLE
php8 compatability

### PR DESCRIPTION
**Pull request by Alexander1000**

### CODE REVIEW

**Comment by Alexander1000** [comment]
@cataphract, do you need support for older versions (php major version < 7)?

**Comment by Alexander1000** [comment]
how i can add environment with php 8 for running tests on ci/cd system?

**Comment by Alexander1000** [comment]
with php8 while exists problems
on snippen in rararch.c segmentation fault on line:
```
zobj->rar_file = rar;
```
i while find problems)

**Comment by Alexander1000** [comment]
@weltling, HI
I saw you main contributor in php.
Can you prompt about may be implicit breaking changes?

**Comment by Alexander1000** [comment]
```
object_init_ex(object, rararch_ce_ptr);
```
returns FAILURE... hm...

**Comment by cataphract** [comment]
I'd like to support at least 5.6. CI needs a new package in my deb repository. I'll take a look at this and the rest this weekend.

**Comment by Alexander1000** [comment]
cause of failure is flag ZEND_ACC_IMPLICIT_ABSTRACT_CLASS in ce_flags... i while in serch for fix it

**Comment by Alexander1000** [comment]
heh.... find problems)) my bads... add interface, but not implement it...))

**Comment by Alexander1000** [comment]
In local tests on PHP8 passed
```
FROM debian:buster-20201012

RUN apt-get update \
    && apt-get install -y \
        curl \
        unzip \
        g++ \
        make \
        pkg-config \
        apt-transport-https \
        lsb-release \
        ca-certificates \
        wget

# install php
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list \
    && apt-get update \
    && apt-get install -y php8.0 php8.0-dev

COPY . /app

WORKDIR /app

RUN cd /app && phpize && ./configure && make clean && make && make install

ENTRYPOINT make test
```

**Comment by cataphract** [comment]
I've implemented support in https://github.com/cataphract/php-rar/commit/d95cab037b193ba209951a88eb5ca2e96f1cce46 . Thanks for your contribution.

**Comment by Dibbyo456** [comment]
@Alexander1000 Just wanted to say thank you sooo much for adding PHP 8 compatibility.

**Pull request closed without merging**
